### ISSUE TITLE
Getting both overcooked-ai and overcooked-demo working together.

### ISSUE THREAD

**Issue by Cpache1** [HumanCompatibleAI/overcooked-demo#21]
So, I have been attempting to make this repository work with the main overcooked_ai one and I have run into some issues. For reference, I was attempting to do the Overcooked-Demo-Legacy installation as I need and prefer the .js backend.

1. when following the instructions, the initial 'npm install' does nothing.

![image](https://user-images.githubusercontent.com/23500321/91996196-a0c99500-ed30-11ea-917c-6c08751ff3e6.png)

Given the previous errors ("no such file"), I figure it had something to do with a missing "cd overcooked-demo-legacy" rather than "cd overcooked-demo" only - so you should add this to your README file. Because once you go into that folder, then you can use 'npm install'. It then gives me this:

![image](https://user-images.githubusercontent.com/23500321/91996743-411fb980-ed31-11ea-8ad1-4e201acb3af8.png)

2. I don't know what it means by "looking for funding" and typing "npm fund" I just get this:

![image](https://user-images.githubusercontent.com/23500321/91997168-b3909980-ed31-11ea-9400-ca4bbf81d658.png)

3. At this point of the instructions I can't proceed anymore. This instruction: "Link to the javascript version of the environment code (this). Linking will warn you about vulnerabilities in overcooked_ai_js" is not working. "this" takes me to a broken link. I still attempted to find the overcooked_ai_js file but it doesn't exist on either the overcooked-ai repo or this one.

How should I proceed?

**Comment by micahcarroll** [comment]
I believe you might be running `npm install` from the wrong directory? You should be running it from `overcooked-demo-legacy` (the instructions for the legacy code have not been updated to reflect the division between legacy and non-legacy code).

**Comment by Cpache1** [comment]
I see. What I was trying to do is to run the demo on a website with pre-built agents - the ones you made for your paper, discussed in this [blog](https://bair.berkeley.edu/blog/2019/10/21/coordination/) and with which you can play [here](https://humancompatibleai.github.io/overcooked-demo/) or see each other play. Did you use legacy code to set that demo up or latest? Also, is it possible to access those pre-trained bots from your previous study? (I guess that might not be in this repo...if not I am happy to post on the specific repository if you point me to it! :) )

**Comment by micahcarroll** [comment]
The demo [here](https://humancompatibleai.github.io/overcooked-demo/) was made using the legacy code only – so those are in fact the pre-trained bots from the initial study published at NeurIPS! We will be clarifying this in a future update.
