### ISSUE TITLE
Have a tutorial on loading a pre-trained agent and letting you play with it

### ISSUE THREAD

**Issue by micahcarroll** [HumanCompatibleAI/overcooked-demo#39]

**Comment by upasana27** [comment]
I tried following this guide: https://github.com/HumanCompatibleAI/overcooked-demo/tree/master/server/static/assets/agents/RllibSelfPlay_CrampedRoom to add my pretrained rllib agent and play with it, however that didn't work. Trying to lead the already given example doesn't work either as shown in attached picture. Is there an ray compatibility issue, as I saw when the tutorial was pushed into this repository, the corresponding ray version in human aware rl repository was lower, is that the issue?

**Comment by micahcarroll** [comment]
Resolving in new overcooked-demo within overcooked-ai
