### ISSUE TITLE
save trajectories in human-human mode

### ISSUE THREAD

**Issue by AlexWanghaoming** [HumanCompatibleAI/overcooked-demo#40]
Hi,
I would like to train my BC model. How could I save trajectories in human-human mode? 
Thanks

**Comment by micahcarroll** [comment]
We currently don't have an easy way to save human-human data (we're working on cleaning up that code). You can save human-AI trajectories from the [demo website](https://humancompatibleai.github.io/overcooked-demo/), or try to change the human-AI [user study code](https://github.com/HumanCompatibleAI/overcooked-hAI-exp) to allow for two different participants.

**Comment by AnnieJohnson25** [comment]
Where is the code for the demo website available?

**Comment by micahcarroll** [comment]
Are you talking about [this website](https://humancompatibleai.github.io/overcooked-demo/)? If so it's on the `gh-pages` branch of this repo

**Comment by micahcarroll** [comment]
Currently resolving this issue here: https://github.com/HumanCompatibleAI/overcooked_ai/issues/115
