### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by anavc97** [HumanCompatibleAI/overcooked-demo#44]
I've been trying to run a first build of the demo but I get this error:

```
 => => naming to docker.io/library/overcooked-demo_app                                         0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network overcooked-demo_default  Created                                                    0.1s
 ⠿ Container overcooked-demo-app-1  Created                                                    0.1s
Attaching to overcooked-demo-app-1
Error response from daemon: driver failed programming external connectivity on endpoint overcooked-demo-app-1 (4bcc12b01a8dfbf43e45318ecaaa79651e64a6aa7f483b3be00abb1738c42272): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
```
The `lsof -i :80` returns nothing.

I'm running in a dual boot with windows 10 and Ubuntu Focal 20.04

- Manual installation of docker version: 
```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Docker Compose version v2.6.0

I've tried restart the PC and the docker service, to no avail.

Thank you for your help.

**Comment by jyan1999** [comment]
Hi @anavc97, I am looking into this issue right now. In the meantime, have you tried forwarding to a different port on the host machine? You just need to change the port number on [this line](https://github.com/HumanCompatibleAI/overcooked-demo/blob/edd94083bfdbf77c4a3f990ae9d52d94d23bc922/docker-compose.yml#L15) and [this line](https://github.com/HumanCompatibleAI/overcooked-demo/blob/edd94083bfdbf77c4a3f990ae9d52d94d23bc922/server/app.py#L562) to a different port.

**Comment by anavc97** [comment]
Hello @jyan1999! Thank you for your time. I am actually not gonna use this machine anymore, so I should mark this issue as resolved. Thank you regardless.
